
campus: 'Fresno'
work_type: "default"
metadata_file: "mets.xml"
depositor: kcloud@calstate.edu
input_dir: /data/exported/
handle_report: /data/tmp/MAIN_handle_report.txt
admin_set_id: 'v118rd525'

# exit_on_error: when an AIP package encounters an error should the import process end or continue?
# true - ends processing on error
# false - continues processing
exit_on_error: false

# output_level: How much will be output to the shell while running
# quiet - Nothing will be output
# minimal - a running progress bar will be output
# verbose - running progress text will be output
output_level: 'verbose'

include_thumbnail: false

# Enter University eg, California State University, <name>
default_university: California State University, Fresno

# work map from resource_type.
# values are value_mapped_to_resource_type: Work Type
type_to_work_map:
  Thesis: Thesis
  Dissertation: Thesis
  Project: Thesis
  Graduate Project: Thesis
  Student Research: Thesis
  Newspaper: Publication
  Journal Issue: Publication
  Poster: Publication
  Report: Publication
  Preprint: Publication
  Technical Report: Publication
  Translation: Publication
  Poetry: Publication
  Working Paper: Publication
  Learning Object: EducationalResource
  Text: Publication
  Dataset: Dataset
  Abstract: Thesis
  Article: Publication
  Articles: Publication
  Blog: Publication
  Book Chapter: Publication
  Book: Publication
  Conference Proceeding: Publication
  Doctoral Project: Thesis
  Journal: Publication
  Letter: Publication
  Magazine: Publication
  News Release: Publication
  Poem: Publication
  Review: Publication
  Slides: Publication
  Presentation: Publication
  Photographic Image: Publication
  Image: Publication
  Video - Other: Publication
  Flyer: Publication
  Interview: Publication
  Webinar: Publication

DSpace COMMUNITY:
  desc_metadata_prefix: "//dim:dim[@dspaceType='COMMUNITY']"
  namespace:
    xmlns: http://www.loc.gov/METS/
    dim: http://www.dspace.org/xmlns/dspace/dim

DSpace COLLECTION:
  desc_metadata_prefix: "//dim:dim[@dspaceType='COLLECTION']"
  namespace:
    xmlns: http://www.loc.gov/METS/
    dim: http://www.dspace.org/xmlns/dspace/dim

DSpace ITEM:
  desc_metadata_prefix: "//xmlns:mdWrap[@OTHERMDTYPE='DIM']/xmlns:xmlData/dim:dim[@dspaceType='ITEM']"
  namespace:
    xmlns: http://www.loc.gov/METS/
    dim: http://www.dspace.org/xmlns/dspace/dim

# Dublin Core Field Mapping
fields:
  # Notes following 5/8 meeting w/Fresno
  # UNCOMMENT for path to 'abstract'
  # CHANGE xpath to 'description' to add Fresno dc.description
  # - "/dim:field[@mdschema='dc'][@element='description'][not(@qualifier)]"
  #abstract:
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='abstract']"
  #  type: Array
  description:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='abstract']"
    type: Array
  advisor:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='advisor'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='advisor']"
    type: Array
  alternative_title:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='title'][@qualifier='alternative']"
    type: Array
  bibliographic_citation:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='identifier'][@qualifier='citation']"
    type: Array
  college:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='sponsorship']"
    type: Array
  committee_member:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='committeemember']"
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='committeeMember']"
    type: Array
  contributor:
    xpath:
      #- "/dim:field[@mdschema='dc'][@element='contributor'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='Interviewee']"
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='Interviewer']"
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='Narrator']"
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='illustrator']"
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='other']"
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='photographer']"
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='player']"
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='presenter']"
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='reviewer']"
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='speaker']"
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='translator']"
    type: Array
  creator:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='author']"
      - "/dim:field[@mdschema='dc'][@element='creator'][not(@qualifier)]"
    type: Array
  date_accessioned:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='accessioned']"
    type: String
  date_created:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='created']"
      - "/dim:field[@mdschema='dc'][@element='date'][not(@qualifier)]"
    type: Array
  date_copyright:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='copyright']"
    type: Array
  date_issued:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='issued']"
    type: Array
  date_modified:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='updated']"
    type: String
  # date_published:
  #  xpath:
  #    - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='published']"
  #  type: String
  date_submitted:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='date'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='submitted']"
    type: Array
  date_uploaded:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='available']"
    type: String
  degree_name:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='degree'][not(@qualifier)]"
    type: Array
  description_note:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='illustration']"
      - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='reference']"
      - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='tableofcontents']"
      - "/dim:field[@mdschema='dc'][@element='description'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='relation'][@qualifier='hasformatof']"
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='local']"
      - "/dim:field[@mdschema='dc'][@element='contributor'][not(@qualifier)]"
    type: Array
  department:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='department']"
    type: Array
  editor:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='editor']"
    type: Array
  embargo_release_date:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='embargountil']"
    type: String
  embargo_terms:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='embargoterms']"
    type: String
  extent:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='format'][@qualifier='extent']"
      - "/dim:field[@mdschema='dc'][@element='format'][@qualifier='medium']"
      - "/dim:field[@mdschema='dc'][@element='format'][not(@qualifier)]"
    type: Array
  geographical_area:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='coverage'][@qualifier='spatial']"
    type: Array
  handle:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='identifier'][@qualifier='uri']"
    type: Array
  identifier:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='identifier'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='identifier'][@qualifier='other']"
      #- "/dim:field[@mdschema='dc'][@element='subject'][@qualifier='lcc']"
      - "/dim:field[@mdschema='dc'][@element='identifier'][@qualifier='coursenumber']"
    type: Array
  identifier_uri:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='relation'][@qualifier='hasversion']"
    type: Array
  is_part_of:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='relation'][@qualifier='ispartofseries']"
      - "/dim:field[@mdschema='dc'][@element='relation'][@qualifier='ispartof']"
    type: Array
  isbn:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='identifier'][@qualifier='isbn']"
    type: Array
  issn:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='identifier'][@qualifier='issn']"
    type: Array
  keyword:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='relation'][@qualifier='journal']"
    type: Array
  language:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='language'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='language'][@qualifier='iso']"
    type: Array
  license:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='rights'][@qualifier='license']"
    type: Array
  provenance:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='provenance']"
      - "/dim:field[@mdschema='dc'][@element='provenance'][not(@qualifier)]"
    type: Array
  publisher:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='publisher'][not(@qualifier)]"
      #- "/dim:field[@mdschema='dc'][@element='issuer'][not(@qualifier)]"
      #- "/dim:field[@mdschema='dc'][@element='relation'][@qualifier='journal']"
    type: Array
  related_url:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='relation'][@qualifier='uri']"
    type: Array
  resource_type:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='type'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='type'][@qualifier='genre']"
    type: Array
  rights_holder:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='rights'][@qualifier='holder']"
    type: Array
  rights_note:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='rights'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='statementofresponsibility']"
      - "/dim:field[@mdschema='dc'][@element='rights'][@qualifier='notice']"
    type: Array
  rights_uri:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='rights'][@qualifier='uri']"
    type: Array
  sponsor:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='sponsor']"
      - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='sponsorship']"
      - "/dim:field[@mdschema='dc'][@element='coverage'][@qualifier='sponsor']"
    type: Array
  subject:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='subject'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='subject'][@qualifier='category']"
      - "/dim:field[@mdschema='dc'][@element='subject'][@qualifier='classification']"
      - "/dim:field[@mdschema='dc'][@element='subject'][@qualifier='lcsh']"
      - "/dim:field[@mdschema='dc'][@element='subject'][@qualifier='other']"
    type: Array
  time_period:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='coverage'][@qualifier='temporal']"
      - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='event']"
    type: Array
  title:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='title'][not(@qualifier)]"
    type: Array
