
campus: 'Northridge'
work_type: "default"
metadata_file: "mets.xml"
depositor: kcloud@calstate.edu
input_dir: /data/exported/
admin_set_id: 'zc77sq08x'

# exit_on_error: when an AIP package encounters an error should the import process end or continue?
# true - ends processing on error
# false - continues processing
exit_on_error: false

# output_level: How much will be output to the shell while running
# quiet - Nothing will be output
# minimal - a running progress bar will be output
# verbose - running progress text will be output
output_level: 'verbose'

include_thumbnail: false

# Enter University eg, California State University, <name>
default_university: California State University, Northridge

# work map from resource_type.
# values are value_mapped_to_resource_type: Work Type
type_to_work_map:
  Abstract: Publication
  Agenda: Publication
  Animation: Publication
  Article: Publication
  Book: Publication
  Book review: Publication
  Book Chapter: Publication
  Conference paper or proceedings: Publication
  Conference program: Publication
  Course Materials: EducationalResource
  Dataset: DataSet
  Exercise: EducationalResource
  Interview: Publication
  Journal: Publication
  Learning Object: EducationalResource
  Letters: Publication
  Liner notes: Publication
  Poster: Publication
  Preface: Publication
  Presentation: Publication
  Project: Publication
  Dissertation: Thesis
  Graduate project: Thesis
  Thesis: Thesis
  Audio recording: Thesis
  Video: Thesis
  Table: Thesis
  Plan or blueprint: Thesis
  Map: Thesis
  Image: Thesis
  Script: Thesis
  Software: Thesis
  Newsletter: Publication
  Pamphlet: Publication
  Postcard: Publication
  Bulletin: Publication
  Learning object: EducationalResource
  Tutorial: EducationalResource
  Technical Report: Publication
  Web page: Publication
  Report: Publication
  Conference proceedings: Publication
  # first pass
  # Book chapter: Publication
  # second pass
  # Book chapter: Thesis

# Dublin Core Field Mapping
fields:
  description:
    xpath:
      #- "/dim:field[@mdschema='dc'][@element='description'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='abstract']"
    type: Array
  advisor:
    xpath:
     - "/dim:field[@mdschema='dc'][@element='advisor'][not(@qualifier)]"
     - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='advisor']"
   type: Array
  alternative_title:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='title'][@qualifier='alternative']"
    type: Array
  bibliographic_citation:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='identifier'][@qualifier='citation']"
    type: Array
  college:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='department']"
    type: Array
  committee_member:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='committeemember']"
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='committeeMember']"
    type: Array
  contributor:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='contributor'][not(@qualifier)]"
      # Need to look at field below; yes to contrib for some works, no for others
   #  - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='other']"
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='photographer']"
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='illustrator']"
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='corporate']"
    type: Array
  creator:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='author']"
      - "/dim:field[@mdschema='dc'][@element='creator'][not(@qualifier)]"
    type: Array
  date_accessioned:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='accessioned']"
    type: String
  date_copyright:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='copyright']"
    type: Array
  date_created:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='created']"
    # - "/dim:field[@mdschema='dc'][@element='date'][not(@qualifier)]"
    type: Array
  date_issued:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='issued']"
    type: Array
  date_modified:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='updated']"
    type: String
  date_submitted:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='date'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='submitted']"
    type: Array
  date_uploaded:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='available']"
    type: String
  degree_level:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='degree']"
    type: String
  description_note:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='source'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='note'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='description'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='version']"
      - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='note']"
      - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='tableofcontents']"
      - "/dim:field[@mdschema='dc'][@element='relation'][@qualifier='isversionof']"
      - "/dim:field[@mdschema='dc'][@element='relation'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='relation'][@qualifier='hasversionof']"
    type: Array
  department:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='department']"
    type: Array
  doi:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='relation'][@qualifier='requires']"
    type: Array
  editor:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='editor']"
    type: Array
  embargo_release_date:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='date'][@qualifier='embargountil']"
    type: String
  embargo_terms:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='embargoterms']"
    type: String
  extent:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='format'][@qualifier='extent']"
    type: Array
  geographical_area:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='coverage'][@qualifier='spatial']"
    type: Array
  handle:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='identifier'][@qualifier='uri']"
    type: Array
  identifier:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='identifier'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='identifier'][@qualifier='isbn']"
      - "/dim:field[@mdschema='dc'][@element='identifier'][@qualifier='issn']"
      - "/dim:field[@mdschema='dc'][@element='identifier'][@qualifier='other']"
      - "/dim:field[@mdschema='dc'][@element='subject'][@qualifier='lcc']"
    type: Array
  identifier_uri:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='identifier'][@qualifier='orcid']"
      #- "/dim:field[@mdschema='dc'][@element='relation'][@qualifier='requires']"
    type: Array
  is_part_of:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='relation'][@qualifier='ispartofseries']"
      - "/dim:field[@mdschema='dc'][@element='relation'][@qualifier='ispartof']"
    type: Array
  issn:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='identifier'][@qualifier='issn']"
    type: Array
  isbn:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='identifier'][@qualifier='isbn']"
    type: Array
  language:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='language'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='language'][@qualifier='iso']"
    type: Array
  provenance:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='provenance']"
      - "/dim:field[@mdschema='dc'][@element='provenance'][not(@qualifier)]"
    type: Array
  publisher:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='publisher'][not(@qualifier)]"
    type: Array
  related_url:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='relation'][@qualifier='uri']"
      - "/dim:field[@mdschema='dc'][@element='source'][@qualifier='uri']"
    type: Array
  resource_type:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='type'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='type'][@qualifier='genre']"
      # Genre provides TSM or other genre relations, not 'works' eg. Opera
      #- "/dim:field[@mdschema='dc'][@element='genre'][not(@qualifier)]"
    type: Array
  rights_note:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='rights'][not(@qualifier)]"
    type: Array
  rights_holder:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='rights'][@qualifier='holder']"
    type: Array
  rights_uri:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='rights'][@qualifier='uri']"
    type: Array
  statement_of_responsibility:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='statement_of_responsibility']"
      - "/dim:field[@mdschema='dc'][@element='description'][@qualifier='statementofresponsibility']"
    type: Array
  sponsor:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='sponsor'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='contributor'][@qualifier='sponsor']"
    type: Array
  subject:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='subject'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='subject'][@qualifier='other']"
      - "/dim:field[@mdschema='dc'][@element='subject'][@qualifier='lcsh']"
      - "/dim:field[@mdschema='dc'][@element='subject'][@qualifier='lcc']"
      - "/dim:field[@mdschema='dc'][@element='subject'][@qualifier='category']"
      - "/dim:field[@mdschema='dc'][@element='audience'][not(@qualifier)]"
      - "/dim:field[@mdschema='dc'][@element='source'][not(@qualifier)]"
    type: Array
  time_period:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='coverage'][@qualifier='temporal']"
    type: Array
  title:
    xpath:
      - "/dim:field[@mdschema='dc'][@element='title'][not(@qualifier)]"
    type: Array
